. test/test_raises.py::test_case01
F test/test_raises.py::test_case02
 def test_case02():
         with pytest.raises(Exception):
             x = 1 / 1
 >           print("x => %i" % x)
 E           Failed: DID NOT RAISE <class 'Exception'>
 
 test/test_raises.py:19: Failed
